config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out
  resources :users, :except => [:index, :destroy] do
    resources :photos
  end
end

app/models/photo.rb
class Photo <ActiveRecord::Base
  belongs_to :user
  has_attached_file :picture, styles: {medium: "300", thumb: "100x100#" }
  validates_attachment :picture, presence: true, content_type: {:content_type => /\Aimage/}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :name, :email, :password, :password_confirmation
  validates :name, :email, presence: true
  before_save :encrypt_password
  has_many :photos

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def encrypt_password
    unless password.nil?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @photo = Photo.new
  end

  def create
    @user = User.find(params[:user_id])
    @photo = @user.photos.new(photo_params)
    render :new
  end

  private
    def photo_params
      params.require(:photo).permit(:picture)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "I don't trust you. How do I know you're really you?"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome Aboard!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem creating your account. Sucka."
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = @user.name + " your profile is updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome to Stickr</h1>
<h3><%= link_to "Log In", log_in_path %></h3>
<h3><%= link_to "Register", new_user_path %></h3>

app/views/layouts/_errors.html.erb
<div class="errors">
  <% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liqur-The Alcohol Photo Sharing Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="flash">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
  </div>
<%= yield %>

</body>
</html>

app/views/layouts/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for User.new do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Sign Up" %>
<% end %>

app/views/photos/new.html.erb
<h5>Add a photo</h5>

<%= form_for [@user, @photo], :html => { :multipart => true } do |form| %>
  <%= form.file_field :picture %>
  <%= form.submit "Add a photo" %>
<% end %>


<h2><%= @user.name %>'s Liqur Stickrz</h2>
<% if @user.photos.any? %>
  <ul>
    <% @user.photos.each do |photo| %>
      <li>
        <%= image_tag(photo.picture.url(:thumb)) %>
      </li>
    <% end %>
  </ul>



<% else %>
  <p>You're unstuck!</p>
<% end %>

app/views/users/_form.html.erb
<%= render 'layouts/errors', object: @user %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit <%= @user.name %> info </h2>

<%= render 'form' %>

<h5>Your Avatar</h5>
<%= form_for @user, :url => user_path(@user), :html => { :multipart => true} do | form | %>
  <%= form.file_field :avatar %>
  <%= form.submit "Addvatar" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h2> Welcome back, <%= @user.name %>! </h2>


<%= image_tag @user.avatar.url(:medium) %>


<h3><%= link_to "Add photo", new_user_photo_path(@user) %></h3>
<h3><%= link_to "Edit", edit_user_path %></h3>
<h3><%= link_to "Log Out", log_out_path %> </h3>